# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Checkout < Formula
  desc "Checkout is a tool for checking out new git branch with naming convention"
  homepage "https://github.com/mrados7/homebrews"
  version "0.0.23"
  license "MIT"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mrados7/go-git-commands/releases/download/v0.0.23/go-git-commands_0.0.23_darwin_amd64.tar.gz"
      sha256 "406bd86986d0f00b1abedaa4472d6ffce6cf0da5113f3b0cb0988914086408f6"

      def install
        bin.install "checkout"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mrados7/go-git-commands/releases/download/v0.0.23/go-git-commands_0.0.23_darwin_arm64.tar.gz"
      sha256 "d601657059f3acb08d9d6116e29ef22c5c905bdd8607abbc0437b43f6ccc112b"

      def install
        bin.install "checkout"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mrados7/go-git-commands/releases/download/v0.0.23/go-git-commands_0.0.23_linux_arm64.tar.gz"
      sha256 "8134193bf096837c169718a5fe05b96440e783e61f760728d2f5a82742c7098c"

      def install
        bin.install "checkout"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/mrados7/go-git-commands/releases/download/v0.0.23/go-git-commands_0.0.23_linux_armv6.tar.gz"
      sha256 "b2bbf1622ee1d33c6804b7e0796e124509d26175b1f4c622c688ba05c22525d2"

      def install
        bin.install "checkout"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mrados7/go-git-commands/releases/download/v0.0.23/go-git-commands_0.0.23_linux_amd64.tar.gz"
      sha256 "21c5cbc4ece1515bd61c66bb7c90d7f4acb5ebac847f83ee29de89c5f0bb9b0e"

      def install
        bin.install "checkout"
      end
    end
  end

  test do
    system "#{bin}/checkout", "-help"
  end
end
