# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Commit < Formula
  desc "Commit is a tool for commiting changes with naming convention"
  homepage "https://github.com/mrados7/homebrews"
  version "0.0.14"
  license "MIT"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mrados7/go-git-commands/releases/download/v0.0.14/go-git-commands_0.0.14_darwin_amd64.tar.gz"
      sha256 "7176203f5755d24437f124afe6626c47af3af4e939cf2812a53907f244630419"

      def install
        bin.install "commit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mrados7/go-git-commands/releases/download/v0.0.14/go-git-commands_0.0.14_darwin_arm64.tar.gz"
      sha256 "cc82dce562d0f64fc329b0a84d1b52b36ce0c2467f75eaeb38cc406b4ad1a3d3"

      def install
        bin.install "commit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/mrados7/go-git-commands/releases/download/v0.0.14/go-git-commands_0.0.14_linux_armv6.tar.gz"
      sha256 "87706be342d73e6223926c5d2c4bf2d7f354c376050ea03c77e6fa77e2f20109"

      def install
        bin.install "commit"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mrados7/go-git-commands/releases/download/v0.0.14/go-git-commands_0.0.14_linux_amd64.tar.gz"
      sha256 "03ba57ac9c21f3c5364e104cdf10ad94495b0d6b2303178ecf06a8e37149bfce"

      def install
        bin.install "commit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mrados7/go-git-commands/releases/download/v0.0.14/go-git-commands_0.0.14_linux_arm64.tar.gz"
      sha256 "065be560cbb7ad6df949443fb2623d8044528878e0849275e29d0c303fecb51b"

      def install
        bin.install "commit"
      end
    end
  end

  test do
    system "#{bin}/commit", "-help"
  end
end
