# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Commit < Formula
  desc "Commit is a tool for commiting changes with naming convention"
  homepage "https://github.com/mrados7/homebrews"
  version "0.0.30"
  license "MIT"

  depends_on "git"

  on_macos do
    on_intel do
      url "https://github.com/mrados7/go-git-commands/releases/download/v0.0.30/go-git-commands_0.0.30_darwin_amd64.tar.gz"
      sha256 "f644ae6c9d0874603fb3ca6cdf2eb3419791b030587cdcdb75f2a221289db43b"

      def install
        bin.install "commit"
      end
    end
    on_arm do
      url "https://github.com/mrados7/go-git-commands/releases/download/v0.0.30/go-git-commands_0.0.30_darwin_arm64.tar.gz"
      sha256 "43e91fa96eef0ee1cdbd00fe198bf8f9540736dd546a8b30dcc492448f2f1e49"

      def install
        bin.install "commit"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mrados7/go-git-commands/releases/download/v0.0.30/go-git-commands_0.0.30_linux_amd64.tar.gz"
        sha256 "a1eeb359e7c63e910c645d15fb682750bf011d63ae1a2654e80e5158242271ca"

        def install
          bin.install "commit"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/mrados7/go-git-commands/releases/download/v0.0.30/go-git-commands_0.0.30_linux_armv6.tar.gz"
        sha256 "a97aca8af848cb0239ea9e3beac07c8036aa8d6c70133cb47743ae7cb2efb94b"

        def install
          bin.install "commit"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mrados7/go-git-commands/releases/download/v0.0.30/go-git-commands_0.0.30_linux_arm64.tar.gz"
        sha256 "034b06fdf37a11e59bbe719d6975db60db7516f061fb0749a582c55a435b2e8a"

        def install
          bin.install "commit"
        end
      end
    end
  end

  test do
    system "#{bin}/commit", "-help"
  end
end
